name: gost
version: '2.4'
summary: GO Simple Tunnel
description: |
  A simple tunnel written in golang

grade: stable
confinement: strict

apps:
  gost:
    command: bin/gost
    plugs: [network, network-bind, home]

parts:
  go:
    source-tag: go1.8.3
  gost:
    after: [go]
    source: .
    source-type: git
    source-branch: master
    plugin: go
    go-packages: [github.com/ginuerzh/gost/cmd/gost]
    go-importpath: github.com/ginuerzh/gost
  
